{{-- ==========================================================
PAGE: CERTIFICATIONS INDEX
----------------------------------------------------------
Purpose:
Displays and manages all professional certifications
stored in the KaroDev portfolio CMS.

File: resources/views/admin/certifications/index.blade.php

This page follows the same proven structure as the
Experience CMS:

• <x-app-layout>
    • Breeze page header
    • Admin flash messages
    • Existing <x-admin.card> component
        • Tailwind CSS styling
        • Responsive layout

        This prevents the Certifications page from becoming
        a separate unstyled HTML page.
        ========================================================== --}}


        <x-app-layout>


            {{-- ==========================================================
            PAGE HEADER
            ----------------------------------------------------------
            Displays the page title and the primary action button.
            =========================================================== --}}

            <x-slot name="header">

                <div class="flex items-center justify-between gap-4">


                    {{-- Page title --}}

                    <div>

                        <h2 class="font-semibold text-xl text-gray-800 leading-tight">

                            Certifications

                        </h2>

                        <p class="mt-1 text-sm text-slate-500">

                            Manage your professional certifications and credentials.

                        </p>

                    </div>


                    {{-- ==================================================
                    ADD CERTIFICATION BUTTON
                    =================================================== --}}

                    <a href="{{ route('certifications.create') }}" class="inline-flex items-center
                       rounded-lg
                       bg-blue-600
                       px-5 py-2
                       text-sm font-semibold
                       text-white
                       shadow-sm
                       hover:bg-blue-700
                       hover:-translate-y-0.5
                       transition duration-200">

                        + Add Certification

                    </a>

                </div>

            </x-slot>



            {{-- ==========================================================
            MAIN PAGE CONTENT
            =========================================================== --}}

            <div class="py-12">


                <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">


                    {{-- ==================================================
                    FLASH MESSAGES
                    -------------------------------------------------
                    Displays success/error messages generated by
                    CertificationController actions.
                    =================================================== --}}

                    <x-admin.flash-message />



                    {{-- ==================================================
                    CERTIFICATION STATISTICS
                    -------------------------------------------------
                    These cards provide a quick CMS overview.

                    We intentionally use the existing $certifications
                    paginator here rather than introducing additional
                    controller variables at this stage.
                    =================================================== --}}

                    <div class="grid grid-cols-1
                       gap-6
                       mb-6
                       md:grid-cols-2
                       xl:grid-cols-4">


                        {{-- ==================================================
                        TOTAL CERTIFICATIONS
                        =================================================== --}}

                        <div class="rounded-xl
                           bg-white
                           p-6
                           shadow-sm
                           border border-slate-100">

                            <p class="text-sm font-medium text-slate-500">

                                Total Certifications

                            </p>


                            <h3 class="mt-2 text-3xl font-bold text-slate-800">

                                {{ $certifications->total() }}

                            </h3>


                            <p class="mt-1 text-xs text-slate-400">

                                All credentials

                            </p>

                        </div>



                        {{-- ==================================================
                        FEATURED CERTIFICATIONS
                        -------------------------------------------------
                        Counts certifications marked as featured.
                        =================================================== --}}

                        <div class="rounded-xl
                           bg-white
                           p-6
                           shadow-sm
                           border border-slate-100">

                            <p class="text-sm font-medium text-slate-500">

                                Featured

                            </p>


                            <h3 class="mt-2 text-3xl font-bold text-blue-600">

                                {{ \App\Models\Certification::where('featured', true)->count() }}

                            </h3>


                            <p class="mt-1 text-xs text-slate-400">

                                Featured credentials

                            </p>

                        </div>



                        {{-- ==================================================
                        VERIFIED / LINKED CERTIFICATIONS
                        -------------------------------------------------
                        Counts records that have a certificate URL.

                        This gives the CMS a useful indication of how
                        many credentials have supporting verification
                        links.
                        =================================================== --}}

                        <div class="rounded-xl
                           bg-white
                           p-6
                           shadow-sm
                           border border-slate-100">

                            <p class="text-sm font-medium text-slate-500">

                                With Certificate Link

                            </p>


                            <h3 class="mt-2 text-3xl font-bold text-green-600">

                                {{ \App\Models\Certification::whereNotNull('certificate_url')->count() }}

                            </h3>


                            <p class="mt-1 text-xs text-slate-400">

                                Verification available

                            </p>

                        </div>



                        {{-- ==================================================
                        ISSUERS
                        -------------------------------------------------
                        Counts unique organizations that issued the
                        certifications.
                        =================================================== --}}

                        <div class="rounded-xl
                           bg-white
                           p-6
                           shadow-sm
                           border border-slate-100">

                            <p class="text-sm font-medium text-slate-500">

                                Issuing Organizations

                            </p>


                            <h3 class="mt-2 text-3xl font-bold text-orange-600">

                                {{ \App\Models\Certification::query()->distinct('issuer')->count('issuer') }}

                            </h3>


                            <p class="mt-1 text-xs text-slate-400">

                                Unique issuers

                            </p>

                        </div>

                    </div>



                    {{-- ==================================================
                    CERTIFICATION MANAGEMENT CARD
                    -------------------------------------------------
                    The main certification table/search interface
                    begins in Part 2.
                    =================================================== --}}

                    <x-admin.card>


                        {{-- ==================================================
                        SEARCH BAR
                        =================================================== --}}

                        <div class="p-6 border-b">


                            <form method="GET" action="{{ route('certifications.index') }}">

                                <div class="relative">

                                    <input type="text" name="search" value="{{ request('search') }}"
                                        placeholder="Search certification title or issuer..." class="w-full
                                       rounded-lg
                                       border-gray-300
                                       pr-4
                                       focus:border-blue-500
                                       focus:ring-blue-500">

                                </div>

                            </form>

                        </div>



                        {{-- ==================================================
                        PART 1 END
                        -------------------------------------------------
                        Part 2 will contain the certification records
                        table and management actions.
                        =================================================== --}}

                        {{-- ==========================================================
                        CERTIFICATION RECORDS
                        ----------------------------------------------------------
                        Displays every certification returned by the controller.

                        Each record contains:

                        • Certification title
                        • Issuing organization
                        • Issue date
                        • Certificate link
                        • View action
                        • Edit action
                        • Delete action

                        The table uses the same visual language as the
                        existing Experience CMS.
                        =========================================================== --}}

                        <div class="overflow-x-auto">


                            <table class="min-w-full divide-y divide-gray-200">


                                {{-- ==================================================
                                TABLE HEADER
                                =================================================== --}}

                                <thead class="bg-gray-50">

                                    <tr>


                                        {{-- Certification --}}

                                        <th class="px-6 py-3
                                           text-left
                                           text-xs
                                           font-semibold
                                           uppercase
                                           tracking-wider
                                           text-slate-500">

                                            Certification

                                        </th>


                                        {{-- Issuer --}}

                                        <th class="px-6 py-3
                                           text-left
                                           text-xs
                                           font-semibold
                                           uppercase
                                           tracking-wider
                                           text-slate-500">

                                            Issuer

                                        </th>


                                        {{-- Issued --}}

                                        <th class="px-6 py-3
                                           text-left
                                           text-xs
                                           font-semibold
                                           uppercase
                                           tracking-wider
                                           text-slate-500">

                                            Issued

                                        </th>


                                        {{-- Certificate --}}

                                        <th class="px-6 py-3
                                           text-left
                                           text-xs
                                           font-semibold
                                           uppercase
                                           tracking-wider
                                           text-slate-500">

                                            Certificate

                                        </th>


                                        {{-- Featured --}}

                                        <th class="px-6 py-3
                                           text-left
                                           text-xs
                                           font-semibold
                                           uppercase
                                           tracking-wider
                                           text-slate-500">

                                            Featured

                                        </th>


                                        {{-- Actions --}}

                                        <th class="px-6 py-3
                                           text-right
                                           text-xs
                                           font-semibold
                                           uppercase
                                           tracking-wider
                                           text-slate-500">

                                            Actions

                                        </th>

                                    </tr>

                                </thead>



                                {{-- ==================================================
                                TABLE BODY
                                =================================================== --}}

                                <tbody class="divide-y divide-gray-200">


                                    {{-- ==================================================
                                    LOOP THROUGH CERTIFICATIONS
                                    =================================================== --}}

                                    @forelse ($certifications as $certification)


                                                                    <tr class="group
                                                                                                           hover:bg-slate-50
                                                                                                           transition duration-200">


                                                                        {{-- ==================================================
                                                                        CERTIFICATION TITLE
                                                                        =================================================== --}}

                                                                        <td class="px-6 py-5">


                                                                            <div class="flex items-center gap-4">


                                                                                {{-- Certificate Icon --}}

                                                                                <div class="flex h-11 w-11
                                                                                                                       shrink-0
                                                                                                                       items-center
                                                                                                                       justify-center
                                                                                                                       rounded-xl
                                                                                                                       bg-amber-100
                                                                                                                       text-lg
                                                                                                                       text-amber-700
                                                                                                                       transition
                                                                                                                       duration-200
                                                                                                                       group-hover:scale-105">

                                                                                    🏆

                                                                                </div>


                                                                                <div class="min-w-0">


                                                                                    <div class="font-semibold
                                                                                                                           text-slate-800">

                                                                                        {{ $certification->title }}

                                                                                    </div>


                                                                                    <div class="mt-1
                                                                                                                           text-xs
                                                                                                                           text-slate-400">

                                                                                        Professional Credential

                                                                                    </div>

                                                                                </div>

                                                                            </div>

                                                                        </td>



                                                                        {{-- ==================================================
                                                                        ISSUER
                                                                        =================================================== --}}

                                                                        <td class="px-6 py-5">


                                                                            <div class="font-medium
                                                                                                                   text-slate-700">

                                                                                {{ $certification->issuer }}

                                                                            </div>

                                                                        </td>



                                                                        {{-- ==================================================
                                                                        ISSUE DATE
                                                                        ------------------------------------------------
                                                                        Uses issued_at from the Certification model.

                                                                        Carbon formats the database date into
                                                                        a clean human-readable format.
                                                                        =================================================== --}}

                                                                        <td class="px-6 py-5">


                                                                            <span class="text-sm text-slate-600">

                                                                                {{ $certification->issued_at
                                        ? \Carbon\Carbon::parse($certification->issued_at)->format('M Y')
                                        : '—'
                                                                                                            }}

                                                                            </span>

                                                                        </td>



                                                                        {{-- ==================================================
                                                                        CERTIFICATE LINK
                                                                        =================================================== --}}

                                                                        <td class="px-6 py-5">


                                                                            @if ($certification->certificate_url)

                                                                                <a href="{{ $certification->certificate_url }}" target="_blank"
                                                                                    rel="noopener noreferrer" class="inline-flex
                                                                                                                               items-center
                                                                                                                               rounded-lg
                                                                                                                               bg-blue-50
                                                                                                                               px-3 py-2
                                                                                                                               text-sm
                                                                                                                               font-medium
                                                                                                                               text-blue-700
                                                                                                                               hover:bg-blue-100
                                                                                                                               hover:text-blue-800
                                                                                                                               transition
                                                                                                                               duration-200">

                                                                                    View Certificate

                                                                                    <span class="ml-1">

                                                                                        ↗

                                                                                    </span>

                                                                                </a>

                                                                            @else

                                                                                <span class="text-sm
                                                                                                                               text-slate-400">

                                                                                    No link

                                                                                </span>

                                                                            @endif

                                                                        </td>



                                                                        {{-- ==================================================
                                                                        FEATURED STATUS
                                                                        =================================================== --}}

                                                                        <td class="px-6 py-5">


                                                                            @if ($certification->featured)

                                                                                <span class="inline-flex
                                                                                                                               items-center
                                                                                                                               rounded-full
                                                                                                                               bg-green-100
                                                                                                                               px-3 py-1
                                                                                                                               text-sm
                                                                                                                               font-medium
                                                                                                                               text-green-700">

                                                                                    ★ Featured

                                                                                </span>

                                                                            @else

                                                                                <span class="text-slate-400">

                                                                                    —

                                                                                </span>

                                                                            @endif

                                                                        </td>



                                                                        {{-- ==================================================
                                                                        ACTIONS
                                                                        ------------------------------------------------
                                                                        Provides the standard CMS actions:

                                                                        View
                                                                        Edit
                                                                        Delete
                                                                        =================================================== --}}

                                                                        <td class="px-6 py-5">


                                                                            <div class="flex
                                                                                                                   justify-end
                                                                                                                   gap-2">


                                                                                {{-- ==================================================
                                                                                VIEW
                                                                                =================================================== --}}

                                                                                <a href="{{ route('certifications.show', $certification) }}" class="rounded-lg
                                                                                                                       bg-slate-700
                                                                                                                       px-3 py-2
                                                                                                                       text-sm
                                                                                                                       font-medium
                                                                                                                       text-white
                                                                                                                       hover:bg-slate-800
                                                                                                                       hover:-translate-y-0.5
                                                                                                                       transition
                                                                                                                       duration-200">

                                                                                    View

                                                                                </a>



                                                                                {{-- ==================================================
                                                                                EDIT
                                                                                =================================================== --}}

                                                                                <a href="{{ route('certifications.edit', $certification) }}" class="rounded-lg
                                                                                                                       bg-blue-600
                                                                                                                       px-3 py-2
                                                                                                                       text-sm
                                                                                                                       font-medium
                                                                                                                       text-white
                                                                                                                       hover:bg-blue-700
                                                                                                                       hover:-translate-y-0.5
                                                                                                                       transition
                                                                                                                       duration-200">

                                                                                    Edit

                                                                                </a>



                                                                                {{-- ==================================================
                                                                                DELETE
                                                                                ------------------------------------------------
                                                                                DELETE requests require a form because
                                                                                normal links only perform GET requests.
                                                                                =================================================== --}}

                                                                                <form action="{{ route('certifications.destroy', $certification) }}"
                                                                                    method="POST"
                                                                                    onsubmit="return confirm('Delete this certification permanently?')">

                                                                                    @csrf

                                                                                    @method('DELETE')


                                                                                    <button type="submit" class="rounded-lg
                                                                                                                           bg-red-600
                                                                                                                           px-3 py-2
                                                                                                                           text-sm
                                                                                                                           font-medium
                                                                                                                           text-white
                                                                                                                           hover:bg-red-700
                                                                                                                           hover:-translate-y-0.5
                                                                                                                           transition
                                                                                                                           duration-200">

                                                                                        Delete

                                                                                    </button>

                                                                                </form>

                                                                            </div>

                                                                        </td>

                                                                    </tr>


                                    @empty


                                        {{-- ==================================================
                                        EMPTY STATE
                                        ------------------------------------------------
                                        Displayed when no certifications exist or
                                        when the search returns no results.
                                        =================================================== --}}

                                        <tr>

                                            <td colspan="6" class="px-6 py-12
                                                       text-center
                                                       text-slate-500">


                                                <div class="mx-auto
                                                           flex h-14 w-14
                                                           items-center
                                                           justify-center
                                                           rounded-2xl
                                                           bg-amber-100
                                                           text-2xl">

                                                    🏆

                                                </div>


                                                <p class="mt-4
                                                           font-semibold
                                                           text-slate-700">

                                                    No certification records found.

                                                </p>


                                                @if (request('search'))

                                                    <p class="mt-1 text-sm text-slate-400">

                                                        Try another search term.

                                                    </p>

                                                @else

                                                    <p class="mt-1 text-sm text-slate-400">

                                                        Add your first certification to begin
                                                        building your professional credentials.

                                                    </p>

                                                @endif


                                                <a href="{{ route('certifications.create') }}" class="mt-5
                                                           inline-flex
                                                           items-center
                                                           rounded-lg
                                                           bg-blue-600
                                                           px-5 py-2.5
                                                           text-sm
                                                           font-semibold
                                                           text-white
                                                           hover:bg-blue-700
                                                           transition
                                                           duration-200">

                                                    + Add Certification

                                                </a>

                                            </td>

                                        </tr>


                                    @endforelse

                                </tbody>

                            </table>

                        </div>


                        {{-- ==========================================================
                        PAGINATION
                        ----------------------------------------------------------
                        Laravel generates the pagination controls automatically
                        when the controller returns a paginated collection.
                        =========================================================== --}}

                        @if ($certifications->hasPages())

                            <div class="p-6 border-t">

                                {{ $certifications->links() }}

                            </div>

                        @endif

                        {{-- ==========================================================
                        END OF CERTIFICATION MANAGEMENT CARD
                        ----------------------------------------------------------
                        Closes the existing admin card component used throughout
                        the KaroDev CMS.
                        =========================================================== --}}

                    </x-admin.card>


                </div>


                {{-- ==========================================================
                END OF MAIN PAGE CONTENT
                =========================================================== --}}

            </div>


        </x-app-layout>


        {{-- ==========================================================
        END OF CERTIFICATIONS INDEX PAGE
        ========================================================== --}}